version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/star-wars-movie-db
      - JWT_SECRET=clave-secreta
      - SWAPI_URL=https://www.swapi.tech/api
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - star-wars-network

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=star-wars-movie-db
    volumes:
      - mongo_data:/data/db
    networks:
      - star-wars-network

volumes:
  mongo_data:

networks:
  star-wars-network:
    driver: bridge
